name = "ogp-worker"
main = "src/index.tsx"
compatibility_date = "2024-10-01"

# KV Namespaces for template storage
[[kv_namespaces]]
binding = "TEMPLATES"
id = "f2a352ab76304b9997e128ee855dd9d2"
preview_id = "a299b47dfff845059053c95f090d605c"

# R2 Buckets for image storage
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "ogp-images"
