name = "ogp-worker"
main = "src/index.tsx"
compatibility_date = "2024-10-01"

[vars]
API_KEY = "cwe8yxq4mtc-HCZ9ebm"

# KV Namespaces for template storage
[[kv_namespaces]]
binding = "TEMPLATES"
id = "placeholder"
preview_id = "placeholder"

[[rules]]
type = "Data"
globs = ["**/*.ttf"]
fallthrough = true
